server:
  port: 8080

spring:
  main:
    allow-circular-references: true

sky:
  datasource:
    database: sky_take_out
  mybatis:
    type: com.sky.trade.domain.entity
  swagger:
    title: 交易功能接口文档
    package: com.sky.trade.controller

  jwt:
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: af-admin
    # 设置jwt过期时间
    admin-ttl: 7200000
    # 设置前端传递过来的令牌名称
    admin-token-name: token

    # 用户端微信用户生成的jwt令牌
    user-secret-key: af-user
    user-ttl: 7200000
    user-token-name: authentication
  wechat:
    appid: ${sky.wechat.appid}
    secret: ${sky.wechat.secret}
    mchid: ${sky.wechat.mchid}
    mch-serial-no: ${sky.wechat.mch-serial-no}
    private-key-file-path: ${sky.wechat.private-key-file-path}
    api-v3-key: ${sky.wechat.api-v3-key}
    we-chat-pay-cert-file-path: ${sky.wechat.we-chat-pay-cert-file-path}
    notify-url: ${sky.wechat.notify-url}
    refund-notify-url: ${sky.wechat.refund-notify-url}
  shop:
    address: 北京市丰台区丽泽SOHO
  baidu:
    ak: FGuvu3yBQYBCpWsXyXJ2k6juI5k91kQD


